Repository MagnusTerak/Group-d-assignment, pull requests merged in 2024-12, with the labels that each got.

#59 Create gift section on startpage
  index.html
Labels: Feature

#63 Dynamic "About Us" Page with Language Toggle
  about.html
  public/database/aboutUs.json
  src/js/aboutUs.js
  src/js/components/languageToggleBtn.js
  src/js/helpers/languageManager.js
  src/js/main.js
  src/styles/about.scss
Labels: Tech, Feature, JSON

#62 Implementation of "About Us" Page
  images/about-us-img/cinema-seatings.png
  images/about-us-img/crowd.jpg
  images/about-us-img/indoors-decor.jpg
  images/about-us-img/outdoors-fasad.png
  images/about-us-img/retro-1925.png
  images/about-us-img/retro-sign.jpg
  public/database/aboutUs.json
  src/js/aboutUs.js
  src/js/components/languageToggleBtn.js
  src/js/helpers/fadeIn.js
  src/js/helpers/fetchDataHelper.js
  src/js/helpers/languageManager.js
  src/styles/about.scss
  src/styles/languageToggleBtn.scss
Labels: Design, Tech, Feature

#67 Design gift startpage
  index.html
  src/styles/main.scss
Labels: Design, Feature

#65 Feature/create ongoing movie cards 50
  index.html
  src/js/main.js
  src/js/ongoingMovies.js
  src/styles/ongoingMovies.scss
Labels: Feature
